version: '3.6'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: billventory
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql
    ports:
      - 33060:3306
  app:
    image: oele/nginx-php:7.1
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    ports:
      - 80:80